apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - todo-app/manifests/configmap.yaml
  - todo-app/manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/postgres-secret.yaml
  - todo-backend/manifests/postgres.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-generator/manifests/cronjob.yaml
  - todo-backup/manifests/cronjob.yaml
images:
  - name: PROJECT/TODO_APP
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-app
    newTag: "3.5"
  - name: PROJECT/TODO_BACKEND
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-backend
    newTag: "3.5"
  - name: PROJECT/TODO_GENERATOR
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-generator
    newTag: "3.5"
  - name: PROJECT/TODO_BACKUP
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-backup
    newTag: "3.10"
