apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/httproute.yaml
images:
- name: PROJECT/LOG_READER
  newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/log-output-reader
  newTag: 828b5d512589da0e9f88ea61e3a1957684db7580
- name: PROJECT/LOG_WRITER
  newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/log-output-writer
  newTag: 828b5d512589da0e9f88ea61e3a1957684db7580
