apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: log-output-config
          configMap:
            name: log-output-config
      containers:
        - name: log-writer
          image: dwk-log-output-writer:2.5
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
        - name: log-reader
          image: dwk-log-output-reader:2.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
            - name: PING_PONG_URL
              value: http://ping-pong-svc/pings
            - name: INFORMATION_FILE
              value: /config/information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
            - name: log-output-config
              mountPath: /config
              readOnly: true
