apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: log-writer
          image: dwk-log-output-writer:2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
        - name: log-reader
          image: dwk-log-output-reader:2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
            - name: PING_PONG_URL
              value: http://ping-pong-svc:2346/pings
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
