apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: dwk-ping-pong:4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_HOST
              value: postgres-ping-pong-svc
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: pingpong
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
