apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
  - ../..
patches:
  - path: broadcaster-mode.yaml
  - path: disable-backup.yaml
  - path: external-secret.yaml
