apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project
data:
  TODO_APP_PORT: "3000"
  TODO_BACKEND_PORT: "3000"
  IMAGE_FILE: /usr/src/app/files/image.jpg
  IMAGE_CACHE_TTL_MS: "600000"
  TODO_BACKEND_URL: http://todo-backend-svc:2345
  PICSUM_URL: https://picsum.photos/1200
  WIKIPEDIA_RANDOM_URL: https://en.wikipedia.org/wiki/Special:Random
  MAX_TODO_LENGTH: "140"
  REQUEST_BODY_LIMIT_BYTES: "10000"
  DATABASE_HOST: todo-postgres-svc
  DATABASE_PORT: "5432"
  DATABASE_NAME: todos
  DATABASE_USER: postgres
  BACKUP_BUCKET: dwk-todo-backups-588051040645
