apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-claim
spec:
  storageClassName: dwk-todo-image-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
