apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-log-ping-pong-claim
spec:
  storageClassName: dwk-shared-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
