apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: dwk-todo-backend:2.6
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: TODO_BACKEND_PORT
            - name: MAX_TODO_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: MAX_TODO_LENGTH
            - name: REQUEST_BODY_LIMIT_BYTES
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: REQUEST_BODY_LIMIT_BYTES
          ports:
            - containerPort: 3000
