apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: dwk-todo-backend:2.10
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: TODO_BACKEND_PORT
            - name: MAX_TODO_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: MAX_TODO_LENGTH
            - name: REQUEST_BODY_LIMIT_BYTES
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: REQUEST_BODY_LIMIT_BYTES
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3000
